spring:
  profiles:
    active: prod
  application:
    name: LabForge-AI-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labforge_ai
    username: root
    password:
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      ttl: 3600
  session:
    # session配置
    store-type: redis
    # session 30天 过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天 过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.winter.labforgeai.controller
# knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name
# pexels API KEY
pexels:
  api-key:
pixabay:
  api:
    key: "你的key"
    lang: "zh"
    safesearch: true
# 阿里云 DashScope 配置
dashscope:
  api-key: <Your API Key>
  image-model: <Your Image Model>
